package com.framgia.model;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Payments generated by hbm2java
 */
public class Payment {

	private Integer id;
	private int paymentMethod;
	private Integer status;
	private List<Order> orders = new ArrayList<>();

	public Payment() {
	}

	public Payment(int paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public Payment(Integer id, int paymentMethod, Integer status, List<Order> orders) {
		super();
		this.id = id;
		this.paymentMethod = paymentMethod;
		this.status = status;
		this.orders = orders;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(int paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public List<Order> getOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

	

}
