package com.framgia.model;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;

import java.util.List;

/**
 * ShippingInfo generated by hbm2java
 */
public class ShippingInfo{

	private Integer id;
	private String firstName;
	private String lastName;
	private String city;
	private String district;
	private String address;
	private String phone;
	private List<Order> orders = new ArrayList<>();

	public ShippingInfo() {
	}

	public ShippingInfo(String phone) {
		this.phone = phone;
	}

	public ShippingInfo(String firstName, String lastName, String city, String district, String address, String phone,
			List<Order> orders) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.city = city;
		this.district = district;
		this.address = address;
		this.phone = phone;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public List<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

}
