package com.framgia.entity;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail {

	private Integer id;
	private Order order;
	private Product product;
	private float productPrice;
	private int quantity;
	public OrderDetail() {
		super();
		// TODO Auto-generated constructor stub
	}
	public OrderDetail(Integer id, Order order, Product product, float productPrice, int quantity) {
		super();
		this.id = id;
		this.order = order;
		this.product = product;
		this.productPrice = productPrice;
		this.quantity = quantity;
	}
	public OrderDetail(Order order, Product product, float productPrice, int quantity) {
		super();
		this.order = order;
		this.product = product;
		this.productPrice = productPrice;
		this.quantity = quantity;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Order getOrder() {
		return order;
	}
	public void setOrder(Order order) {
		this.order = order;
	}
	public Product getProduct() {
		return product;
	}
	public void setProduct(Product product) {
		this.product = product;
	}
	public float getProductPrice() {
		return productPrice;
	}
	public void setProductPrice(float productPrice) {
		this.productPrice = productPrice;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	
}
