package com.framgia.entity;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;

import java.util.List;

/**
 * ShippingInfo generated by hbm2java
 */
public class ShippingInfo {

	private Integer id;
	private String firstName;
	private String lastName;
	private String city;
	private String district;
	private String address;
	private String phone;
	private List<Order> orders = new ArrayList<>();
	public ShippingInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	public ShippingInfo(Integer id, String firstName, String lastName, String city, String district, String address,
			String phone, List<Order> orders) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.city = city;
		this.district = district;
		this.address = address;
		this.phone = phone;
		this.orders = orders;
	}
	public ShippingInfo(String firstName, String lastName, String city, String district, String address, String phone,
			List<Order> orders) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.city = city;
		this.district = district;
		this.address = address;
		this.phone = phone;
		this.orders = orders;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public List<Order> getOrders() {
		return orders;
	}
	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

	
}
