package com.framgia.bean;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;

import java.util.List;

/**
 * Carts generated by hbm2java
 */
public class CartInfo {

	private Integer id;
	private UserInfo user;
	private Integer status;
	private List<CartDetailInfo> cartDetails = new ArrayList<CartDetailInfo>();
	public CartInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	public CartInfo(Integer id, UserInfo user, Integer status, List<CartDetailInfo> cartDetails) {
		super();
		this.id = id;
		this.user = user;
		this.status = status;
		this.cartDetails = cartDetails;
	}
	public CartInfo(UserInfo user, Integer status, List<CartDetailInfo> cartDetails) {
		super();
		this.user = user;
		this.status = status;
		this.cartDetails = cartDetails;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public UserInfo getUserInfo() {
		return user;
	}
	public void setUserInfo(UserInfo user) {
		this.user = user;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public List<CartDetailInfo> getCartDetailInfo() {
		return cartDetails;
	}
	public void setCartDetailInfo(List<CartDetailInfo> cartDetails) {
		this.cartDetails = cartDetails;
	}

	
}
