package com.framgia.bean;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Orders generated by hbm2java
 */
public class OrderInfo {

	private Integer id;
	private PaymentInfo payment;
	private ShippingInfoBean shippingInfo;
	private UserInfo user;
	private Date createDate;
	private float totalBill;
	private Integer status;
	private List<OrderDetailInfo> orderDetails = new ArrayList<>();
	public OrderInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	public OrderInfo(Integer id, PaymentInfo payment, ShippingInfoBean shippingInfo, UserInfo user, Date createDate, float totalBill,
			Integer status, List<OrderDetailInfo> orderDetails) {
		super();
		this.id = id;
		this.payment = payment;
		this.shippingInfo = shippingInfo;
		this.user = user;
		this.createDate = createDate;
		this.totalBill = totalBill;
		this.status = status;
		this.orderDetails = orderDetails;
	}
	public OrderInfo(PaymentInfo payment, ShippingInfoBean shippingInfo, UserInfo user, Date createDate, float totalBill,
			Integer status, List<OrderDetailInfo> orderDetails) {
		super();
		this.payment = payment;
		this.shippingInfo = shippingInfo;
		this.user = user;
		this.createDate = createDate;
		this.totalBill = totalBill;
		this.status = status;
		this.orderDetails = orderDetails;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public PaymentInfo getPayment() {
		return payment;
	}
	public void setPayment(PaymentInfo payment) {
		this.payment = payment;
	}
	public ShippingInfoBean getShippingInfo() {
		return shippingInfo;
	}
	public void setShippingInfo(ShippingInfoBean shippingInfo) {
		this.shippingInfo = shippingInfo;
	}
	public UserInfo getUser() {
		return user;
	}
	public void setUser(UserInfo user) {
		this.user = user;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public float getTotalBill() {
		return totalBill;
	}
	public void setTotalBill(float totalBill) {
		this.totalBill = totalBill;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public List<OrderDetailInfo> getOrderDetails() {
		return orderDetails;
	}
	public void setOrderDetails(List<OrderDetailInfo> orderDetails) {
		this.orderDetails = orderDetails;
	}

	
}
