package com.framgia.bean;
// Generated Dec 14, 2018 4:21:20 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Payments generated by hbm2java
 */
public class PaymentInfo {

	private Integer id;
	private int paymentMethod;
	private Integer status;
	private List<OrderInfo> orders = new ArrayList<>();
	public PaymentInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	public PaymentInfo(Integer id, int paymentMethod, Integer status, List<OrderInfo> orders) {
		super();
		this.id = id;
		this.paymentMethod = paymentMethod;
		this.status = status;
		this.orders = orders;
	}
	public PaymentInfo(int paymentMethod, Integer status, List<OrderInfo> orders) {
		super();
		this.paymentMethod = paymentMethod;
		this.status = status;
		this.orders = orders;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getPaymentMethod() {
		return paymentMethod;
	}
	public void setPaymentMethod(int paymentMethod) {
		this.paymentMethod = paymentMethod;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public List<OrderInfo> getOrders() {
		return orders;
	}
	public void setOrders(List<OrderInfo> orders) {
		this.orders = orders;
	}

	
}
